/** Digital input I/O catalog items (DI-*). Edit to extend — no code changes needed. */
import type { CatalogItem } from "../../types/io";

export const DIGITAL_INPUT_ITEMS: CatalogItem[] = [
  {
    tag: "DI-701",
    name: "ESD Pushbutton",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "DI-702",
    name: "Gas Detector Alarm",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "DI-703",
    name: "Vibration Switch",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "DI-704",
    name: "Cooler Fan 1 Fault",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-705",
    name: "Cooler Fan 2 Fault",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-706",
    name: "Pre-Lube Pump Run",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-707",
    name: "Pre-Lube Pump Fault",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-708",
    name: "Starter Motor Run",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-709",
    name: "Local/Remote Selector",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-710",
    name: "Run Permissive",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-711",
    name: "Maintenance Mode Selector",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "DI-712",
    name: "Generic Spare DI",
    category: "Input",
    signal: "DryContact",
    range: "",
    hardwareHint: "DI",
    formC: false,
    tcType: null,
    group: "Digital Inputs",
    inRecommended: false,
    inLimited: false,
  },
];
