/** Analog and digital output catalog items (AO-* / DO-*). Edit to extend. */
import type { CatalogItem } from "../../types/io";

export const ANALOG_OUTPUT_ITEMS: CatalogItem[] = [
  {
    tag: "AO-801",
    name: "Fuel Valve Position",
    category: "Output",
    signal: "4-20mA",
    range: "0-100 %",
    hardwareHint: "AO",
    formC: false,
    tcType: null,
    group: "Analog Outputs",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "AO-802",
    name: "Recycle Valve Position",
    category: "Output",
    signal: "4-20mA",
    range: "0-100 %",
    hardwareHint: "AO",
    formC: false,
    tcType: null,
    group: "Analog Outputs",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "AO-803",
    name: "Cooler Fan VFD Speed Cmd",
    category: "Output",
    signal: "4-20mA",
    range: "0-100 %",
    hardwareHint: "AO",
    formC: false,
    tcType: null,
    group: "Analog Outputs",
    inRecommended: false,
    inLimited: false,
  },
];

export const DIGITAL_OUTPUT_ITEMS: CatalogItem[] = [
  {
    tag: "DO-901",
    name: "Ignition Enable",
    category: "Output",
    signal: "Relay",
    range: "",
    hardwareHint: "DO",
    formC: false,
    tcType: null,
    group: "Digital Outputs",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "DO-902",
    name: "Cooler Fan 1 Start",
    category: "Output",
    signal: "Relay",
    range: "",
    hardwareHint: "DO",
    formC: false,
    tcType: null,
    group: "Digital Outputs",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "DO-903",
    name: "Cooler Fan 2 Start",
    category: "Output",
    signal: "Relay",
    range: "",
    hardwareHint: "DO",
    formC: false,
    tcType: null,
    group: "Digital Outputs",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "DO-904",
    name: "Shutdown Relay (Fail-Safe)",
    category: "Output",
    signal: "Relay-NC",
    range: "",
    hardwareHint: "DO",
    formC: true,
    tcType: null,
    group: "Digital Outputs",
    inRecommended: true,
    inLimited: true,
  },
];
