/** Pressure I/O catalog items (PT-*). Edit to extend — no code changes needed. */
import type { CatalogItem } from "../../types/io";

export const PRESSURE_ITEMS: CatalogItem[] = [
  {
    tag: "PT-101",
    name: "Stage 1 Suction Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-300 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "PT-102",
    name: "Stage 1 Discharge Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-1000 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "PT-201",
    name: "Stage 2 Suction Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-1000 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "PT-202",
    name: "Stage 2 Discharge Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-2500 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "PT-301",
    name: "Stage 3 Suction Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-2500 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "PT-302",
    name: "Stage 3 Discharge Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-5000 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "PT-401",
    name: "Lube Oil Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-100 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "PT-501",
    name: "Fuel Gas Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-100 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "PT-601",
    name: "Crankcase Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-50 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "PT-602",
    name: "Suction Filter Differential Pressure",
    category: "Input",
    signal: "4-20mA",
    range: "0-25 PSI",
    hardwareHint: "AI",
    formC: false,
    tcType: null,
    group: "Pressure",
    inRecommended: false,
    inLimited: false,
  },
];
