/** Temperature I/O catalog items (TT-*). Edit to extend — no code changes needed. */
import type { CatalogItem } from "../../types/io";

export const TEMPERATURE_ITEMS: CatalogItem[] = [
  {
    tag: "TT-101",
    name: "Stage 1 Suction Temperature",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 250 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "TT-102",
    name: "Stage 1 Discharge Temperature",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 400 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "TT-202",
    name: "Stage 2 Discharge Temperature",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 500 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "TT-302",
    name: "Stage 3 Discharge Temperature",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 500 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "TT-401",
    name: "Lube Oil Temperature",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 250 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: true,
  },
  {
    tag: "TT-501",
    name: "Discharge Bottle Temp Stg 1",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 500 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "TT-502",
    name: "Discharge Bottle Temp Stg 2",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 500 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "TT-503",
    name: "Discharge Bottle Temp Stg 3",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 500 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: false,
    inLimited: false,
  },
  {
    tag: "TT-601",
    name: "Cooler Section 1 Outlet Temp",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 250 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: false,
  },
  {
    tag: "TT-602",
    name: "Cooler Section 2 Outlet Temp",
    category: "Input",
    signal: "TC-K",
    range: "-40 to 250 F",
    hardwareHint: "TC",
    formC: false,
    tcType: "K",
    group: "Temperature",
    inRecommended: true,
    inLimited: false,
  },
];
