/**
 * BRAIN+ (BRP1, p/n 20330) port definitions.
 * Each BRAIN+ expansion module adds 8 AI, 4 AO, 6 DO, and 12 TC channels.
 * Up to 2 modules supported (slots P1 and P2).
 */
import type { BrainPlusSlot, Port } from "../types/port";

/**
 * Builds the 12 BRAIN+ thermocouple ports (TC25–TC36) for a slot.
 * Each channel ships wired for Type-K; pin pairs run 27/28…49/50
 * (pin = 27 + 2*(n-25) for TCn).
 */
function brainPlusTcPorts(slot: BrainPlusSlot): Port[] {
  return Array.from({ length: 12 }, (_, i) => {
    const n = i + 25;
    const pin = 27 + 2 * i;
    return {
      id: `TC${n}-${slot}`,
      device: "BRAIN+" as const,
      slot,
      type: "TC" as const,
      label: `TC ${n}`,
      pinNumbers: [pin, pin + 1],
      isFormC: false,
      tcType: "K" as const,
    };
  });
}

function makeBrainPlusPorts(slot: BrainPlusSlot): Port[] {
  return [
    // --- Analog Inputs (AI 13–20, pins 15–22) ---
    {
      id: `AI13-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 13",
      pinNumbers: [15],
      isFormC: false,
    },
    {
      id: `AI14-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 14",
      pinNumbers: [16],
      isFormC: false,
    },
    {
      id: `AI15-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 15",
      pinNumbers: [17],
      isFormC: false,
    },
    {
      id: `AI16-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 16",
      pinNumbers: [18],
      isFormC: false,
    },
    {
      id: `AI17-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 17",
      pinNumbers: [19],
      isFormC: false,
    },
    {
      id: `AI18-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 18",
      pinNumbers: [20],
      isFormC: false,
    },
    {
      id: `AI19-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 19",
      pinNumbers: [21],
      isFormC: false,
    },
    {
      id: `AI20-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AI",
      label: "AI 20",
      pinNumbers: [22],
      isFormC: false,
    },

    // --- Analog Outputs (AO 3, 4, 7, 8 — complements BRAIN's AO 1, 2, 5, 6) ---
    {
      id: `AO3-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AO",
      label: "AO 3",
      pinNumbers: [23],
      isFormC: false,
    },
    {
      id: `AO4-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AO",
      label: "AO 4",
      pinNumbers: [25],
      isFormC: false,
    },
    {
      id: `AO7-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AO",
      label: "AO 7",
      pinNumbers: [24],
      isFormC: false,
    },
    {
      id: `AO8-${slot}`,
      device: "BRAIN+",
      slot,
      type: "AO",
      label: "AO 8",
      pinNumbers: [26],
      isFormC: false,
    },

    // --- Digital Outputs (DO 9–14) — all Form-A (no Form-C on BRAIN+) ---
    {
      id: `DO9-${slot}`,
      device: "BRAIN+",
      slot,
      type: "DO",
      label: "DO 9",
      pinNumbers: [7],
      isFormC: false,
    },
    {
      id: `DO10-${slot}`,
      device: "BRAIN+",
      slot,
      type: "DO",
      label: "DO 10",
      pinNumbers: [8],
      isFormC: false,
    },
    {
      id: `DO11-${slot}`,
      device: "BRAIN+",
      slot,
      type: "DO",
      label: "DO 11",
      pinNumbers: [9],
      isFormC: false,
    },
    {
      id: `DO12-${slot}`,
      device: "BRAIN+",
      slot,
      type: "DO",
      label: "DO 12",
      pinNumbers: [10],
      isFormC: false,
    },
    {
      id: `DO13-${slot}`,
      device: "BRAIN+",
      slot,
      type: "DO",
      label: "DO 13",
      pinNumbers: [11],
      isFormC: false,
    },
    {
      id: `DO14-${slot}`,
      device: "BRAIN+",
      slot,
      type: "DO",
      label: "DO 14",
      pinNumbers: [12],
      isFormC: false,
    },

    // --- Thermocouples (TC 25–36, pin pairs 27/28 through 49/50) ---
    // All channels ship wired for Type-K; generated by brainPlusTcPorts().
    ...brainPlusTcPorts(slot),
  ];
}

export const BRAIN_PLUS_P1_PORTS: Port[] = makeBrainPlusPorts("P1");
export const BRAIN_PLUS_P2_PORTS: Port[] = makeBrainPlusPorts("P2");
